import setuptools

setuptools.setup(
    name="subsamplr",
    version="0.0.1",
    description="A tool for representative subsampling",
    author=u"The LwM Development Team",
    # author_email="",
    license="MIT License",
    keywords=["Subsampling", "living with machines"],
    # long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url="https://github.com/Living-with-machines/subsamplr",
    download_url="https://github.com/Living-with-machines/subsamplr/archive/master.zip",
    packages=setuptools.find_packages(),
    include_package_data=True,
    platforms="OS Independent",
    python_requires='>=3.7',
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Intended Audience :: End Users/Desktop",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "Operating System :: Unix",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: MacOS",
        "Operating System :: OS Independent",
        "Topic :: Software Development",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ]
)
